version: "2"         # required to adjust maintainability checks
checks:
  method-count:
    enabled: false
  method-lines:
    enabled: false
  similar-code:
    enabled: false
plugins:
  scss-lint:
    enabled: true
  markdownlint:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-7"
exclude_patterns:
  - "**/node_modules/"
  - "**/vendor/"
  - "**/Readability.cjs"
  - "**/text-fragment-utils.js"
